INSERT INTO public."PsionicSkillArchetypes" ("name","level","PsionicSchoolID","Description") VALUES 
('Psychic Refinement',0,2,'')
,('Cloak Powers',1,2,'')
,('Psychic Succor',0,1,'')
,('Mastered Succor',1,1,'')
,('Organic Purification Protocols',1,1,'')
,('Remote Repair',1,1,'')
,('Invincible Stand',2,1,'')
,('Major Organ Restoration',2,1,'')
,('Tissue Integrity Field',2,1,'')
,('Accelerated Succor',3,1,'')
;
INSERT INTO public."PsionicSkillArchetypes" ("name","level","PsionicSchoolID","Description") VALUES 
('Metamorph',3,1,'')
,('Teratic Overload',3,1,'')
,('Holistic Optimizartion Patterning',4,1,'')
,('Quintessential Reconstruction',4,1,'')
,('Mindtracing',1,2,'')
,('Synthetic Adaptation',1,2,'')
,('Neural Trap',2,2,'')
,('Psychic Static',2,2,'')
,('Suspended Manifestation',2,2,'')
,('Concert of Minds',3,2,'')
;
INSERT INTO public."PsionicSkillArchetypes" ("name","level","PsionicSchoolID","Description") VALUES 
('Metadimensional Friction',3,2,'')
,('Psychic Tutelage',3,2,'')
,('Surge Momentum',3,2,'')
,('Flawless Mastery',4,2,'')
,('Impervious Pavis of Will',4,2,'')
,('Oracle',0,3,'')
,('Intuitive Response',1,3,'')
,('Sense the Need',1,3,'')
,('Terminal Reflection',1,3,'')
,('Alternate Outcome',2,3,'')
;
INSERT INTO public."PsionicSkillArchetypes" ("name","level","PsionicSchoolID","Description") VALUES 
('Destiny''s Shield',2,3,'')
,('Anguished Vision',3,3,'')
,('Cursed Luck',3,3,'')
,('Forced Outcome',3,3,'')
,('Not My Time',4,3,'')
,('Prophecy',4,3,'')
,('Telekinetic Manipulation',0,4,'')
,('Kinetic Transversal',1,4,'')
,('Pressure Field',1,4,'')
,('Telekinetic Armory',1,4,'')
;
INSERT INTO public."PsionicSkillArchetypes" ("name","level","PsionicSchoolID","Description") VALUES 
('Impact Sump',2,4,'')
,('Slip Field',2,4,'')
,('Telekinetic Expertise',2,4,'')
,('Thermokinesis',2,4,'')
,('Tangible Force Construct',3,4,'')
,('Telekinetic Ram',3,4,'')
,('Reactive Telekinesis',3,4,'')
,('Force Puppetry',4,4,'')
,('Telekinetic Flight',4,4,'')
,('Telepathic Contact',0,5,'')
;
INSERT INTO public."PsionicSkillArchetypes" ("name","level","PsionicSchoolID","Description") VALUES 
('Facile Mind',1,5,'')
,('Transmit Thought',1,5,'')
,('Far Thought',2,5,'')
,('Suppress Cognition',2,5,'')
,('Reflex Response',3,5,'')
,('Telepathic Assault',3,5,'')
,('Memory Editing',4,5,'')
,('Unity of Thought',4,5,'')
,('Personal Apportation',0,6,'')
,('Proficient Apportation',1,6,'')
;
INSERT INTO public."PsionicSkillArchetypes" ("name","level","PsionicSchoolID","Description") VALUES 
('Spatial Awareness',1,6,'')
,('Burdened Apportation',2,6,'')
,('Perceptive Dislocation',2,6,'')
,('Spatial Synchrony Mandala',2,6,'')
,('Effortless Apportation',3,6,'')
,('Stutterjump',3,6,'')
,('Rift Reduplication',3,6,'')
,('Deep Intrusion',4,6,'')
,('Offensive Apportation',4,6,'')
;